CREATE TABLE [dbo].[GC_DataH] (
    [GC_DataID]               INT            NOT NULL,
    [WorkcellID]              INT            NULL,
    [MESCustomer_ID]          INT            NULL,
    [Customer_ID]             INT            NULL,
    [EscapedDate]             DATETIME       NOT NULL,
    [ShiftID]                 INT            NULL,
    [EscapedByEmployeeID_ID]  INT            NOT NULL,
    [EscapedStationID]        INT            NULL,
    [Defect_ID]               INT            NULL,
    [DefectText]              NVARCHAR (200) NULL,
    [CRD]                     NVARCHAR (255) NULL,
    [Description]             NVARCHAR (255) NULL,
    [DetectedByEmployeeID_ID] INT            NULL,
    [DetectedStationID]       INT            NULL,
    [Analysis_ID]             INT            NULL,
    [SerialNumber]            NVARCHAR (50)  NULL,
    [ChildSerialNumber]       NVARCHAR (50)  NULL,
    [DetectedStepIns]         NVARCHAR (50)  NULL,
    [DetectedWindowsUserID]   NVARCHAR (20)  NULL,
    [CRDStepIns]              NVARCHAR (50)  NULL,
    [StartDateTime]           DATETIME       NULL,
    [EscapedStepIns]          NVARCHAR (50)  NULL,
    [EscapedWindowsUserID]    NVARCHAR (20)  NULL,
    [IsMESAutoLinked]         BIT            NULL,
    [LastUpdated]             DATETIME       NULL,
    [LastUpdatedBy]           INT            NULL,
    [Route]                   NVARCHAR (50)  NULL,
    [FailureLabel]            NVARCHAR (100) NULL,
    [ClientName]              VARCHAR (150)  NULL,
    CONSTRAINT [PK_GC_DataH] PRIMARY KEY NONCLUSTERED ([GC_DataID] ASC) ON [PRIMARY]
) ON [INDEXES];

