CREATE TABLE [dbo].[HR_EmployeeTemp] (
    [EmployeeID_ID]     INT            NULL,
    [EmployeeID]        NVARCHAR (20)  NULL,
    [EmployeeIDSAP]     NVARCHAR (20)  NULL,
    [EmployeeName]      NVARCHAR (100) NULL,
    [JoinedDate]        DATETIME       NULL,
    [OperatorGroupName] VARCHAR (100)  NULL,
    [OperatorGroupID]   INT            NULL,
    [CompanyID]         INT            NULL,
    [CompanyName]       VARCHAR (50)   NULL,
    [DepartmentID]      NVARCHAR (30)  NULL,
    [DepartmentName]    VARCHAR (50)   NULL,
    [JobTitle]          NVARCHAR (50)  NULL,
    [PositionID]        INT            NULL,
    [PositionName]      VARCHAR (50)   NULL,
    [ShiftID]           INT            NULL,
    [ShiftName]         VARCHAR (50)   NULL,
    [WorkcellID]        INT            NULL,
    [WorkcellName]      VARCHAR (50)   NULL,
    [Supervisor]        NVARCHAR (100) NULL,
    [IsActive]          BIT            NULL,
    [IsValid]           BIT            NULL,
    [LastUpdated]       DATETIME       NULL,
    [LastUpdatedBy]     INT            NULL,
    [UserName]          VARCHAR (50)   NULL,
    [ErrorMessage]      NVARCHAR (255) NULL,
    [WorkingStatusID]   INT            NULL
);

