CREATE TABLE [dbo].[HR_Employee_eDB] (
    [EmployeeID_ID]       INT            NOT NULL,
    [EmployeeID]          NVARCHAR (20)  NULL,
    [EmployeeIDSAP]       NVARCHAR (20)  NULL,
    [GenderID]            INT            NULL,
    [FullName]            NVARCHAR (100) NULL,
    [ExpJoinedDate]       DATETIME       NULL,
    [JoinedDate]          DATETIME       NULL,
    [IsNotOnBoard]        BIT            NULL,
    [ConvertedDate]       DATETIME       NULL,
    [PITCode]             NVARCHAR (20)  NULL,
    [PITCodeIssuedDate]   DATETIME       NULL,
    [EmployeeTypeID]      INT            NULL,
    [VendorID]            INT            NULL,
    [DepartmentID]        INT            NULL,
    [SectionID]           INT            NULL,
    [WorkcellID]          INT            NULL,
    [EmployeeGroupID]     INT            NULL,
    [CostCenterID]        INT            NULL,
    [EmployeeLevelID]     INT            NULL,
    [IsSupervisor]        BIT            NULL,
    [SupervisorID]        INT            NULL,
    [LocalPositionID]     INT            NULL,
    [IsDL]                BIT            NULL,
    [Email]               NVARCHAR (100) NULL,
    [CompanyPhone]        NVARCHAR (20)  NULL,
    [Ext]                 NVARCHAR (10)  NULL,
    [UserName]            NVARCHAR (50)  NULL,
    [JoinedSDNo]          NVARCHAR (50)  NULL,
    [IsActive]            BIT            NULL,
    [HiredTimeID]         INT            NULL,
    [WorkingStatusID]     INT            NULL,
    [Remarks]             NVARCHAR (255) NULL,
    [DateOfBirth]         DATETIME       NULL,
    [DateofBirthIns]      NVARCHAR (20)  NULL,
    [PlaceOfBirth]        NVARCHAR (50)  NULL,
    [NationallityID]      INT            NULL,
    [PermanentAddress]    NVARCHAR (255) NULL,
    [TemporaryAddress]    NVARCHAR (255) NULL,
    [IDNumber]            NVARCHAR (20)  NULL,
    [IDNumberProvinceID]  INT            NULL,
    [IDNumberIssuedDate]  DATETIME       NULL,
    [IDNumberIssuedPlace] NVARCHAR (255) NULL,
    [OriginText]          NVARCHAR (100) NULL,
    [HandPhone]           NVARCHAR (100) NULL,
    [HomePhone]           NVARCHAR (20)  NULL,
    [PassportNo]          NVARCHAR (20)  NULL,
    [EmergencyContact]    NVARCHAR (255) NULL,
    [InsJoinedDate]       DATETIME       NULL,
    [HINo]                NVARCHAR (50)  NULL,
    [HospitalID]          INT            NULL,
    [SIBookNo]            NVARCHAR (50)  NULL,
    [SIIssuedBy]          NVARCHAR (255) NULL,
    [KindOfSIBookID]      INT            NULL,
    [SIIncludedPackages]  INT            NULL,
    [SIBookStatusID]      INT            NULL,
    [InsEndDate]          DATETIME       NULL,
    [InsRemarks]          NVARCHAR (255) NULL,
    [IsVA]                BIT            NULL,
    [BankAccountNo]       NVARCHAR (50)  NULL,
    [BankKeyID]           INT            NULL,
    [IsReHired]           BIT            NULL,
    [PictureFileName]     NVARCHAR (255) NULL,
    [LastUpdated]         DATETIME       NULL,
    [LastUpdatedBy]       INT            NULL,
    [IsOLE]               BIT            NULL,
    [SiteID]              INT            NULL
);

