CREATE TABLE [dbo].[SC_DomainAccount] (
    [UserName]           NVARCHAR (50)  NOT NULL,
    [EmployeeID_ID]      INT            CONSTRAINT [DF_SC_DomainAccount_EmployeeID_ID] DEFAULT ((0)) NOT NULL,
    [EmployeeID]         NVARCHAR (20)  NULL,
    [EmployeeIDSAP]      NVARCHAR (20)  NULL,
    [Email]              NVARCHAR (100) NULL,
    [DisplayName]        NVARCHAR (100) NULL,
    [Department]         NVARCHAR (100) NULL,
    [Title]              NVARCHAR (100) NULL,
    [Manager]            NVARCHAR (100) NULL,
    [Extension]          NVARCHAR (100) NULL,
    [Mobile]             NVARCHAR (100) NULL,
    [TelephoneNumber]    NVARCHAR (100) NULL,
    [CreatedDate]        DATETIME       NULL,
    [LastLoggonDate]     DATETIME       NULL,
    [PasswordLastSet]    DATETIME       NULL,
    [ExpiredDate]        DATETIME       NULL,
    [AccountIsDisabled]  NVARCHAR (100) NULL,
    [PasswordStatus]     NVARCHAR (255) NULL,
    [AccountExpiresDate] DATETIME       NULL,
    [LastLogon]          DATETIME       NULL,
    [IsServiceAccount]   BIT            NULL,
    [IsValid]            BIT            NULL,
    [Remarks]            NVARCHAR (255) NULL,
    [LastUpdated]        DATETIME       NULL,
    [LastUpdatedBy]      INT            NULL,
    [SupervisorID]       INT            NULL,
    [IsMES]              BIT            NULL,
    [IsMESActive]        BIT            NULL,
    [LogonWorkstation]   VARCHAR (50)   NULL,
    [Path]               VARCHAR (255)  NULL,
    CONSTRAINT [PK_SC_DomainAccount] PRIMARY KEY CLUSTERED ([UserName] ASC)
);

